//! IPC HTTP server for Programmatic Tool Calling.
//!
//! A lightweight HTTP server running on a random localhost port.
//! Python code generated by the SDK calls `POST http://127.0.0.1:{port}/tool/{name}`
//! with JSON args. This server dispatches tool calls through a channel back to
//! the agent loop, which owns all the necessary context (kernel, MCP connections,
//! skill registry, etc.).
//!
//! Architecture:
//! ```text
//! Python → HTTP POST /tool/{name} → IPC server
//!   → sends (name, input) over channel → agent loop
//!   → agent loop calls execute_tool() with full context
//!   → result sent back over oneshot channel → IPC server → Python
//! ```
//!
//! Security: Binds to 127.0.0.1 only — no external access.

use openfang_types::tool::{ToolDefinition, ToolResult};
use std::collections::HashMap;
use std::sync::Arc;
use tokio::net::TcpListener;
use tokio::sync::{mpsc, oneshot};
use tracing::{debug, warn};

/// A request from the IPC server to the agent loop to execute a tool.
pub struct PtcToolRequest {
    /// Tool call ID.
    pub tool_call_id: String,
    /// Tool name to execute.
    pub tool_name: String,
    /// Tool input parameters.
    pub input: serde_json::Value,
    /// Channel to send the result back on.
    pub response_tx: oneshot::Sender<ToolResult>,
}

/// A running PTC IPC server.
pub struct PtcIpcServer {
    /// Port the server is listening on.
    port: u16,
    /// Shutdown signal sender.
    shutdown_tx: Option<oneshot::Sender<()>>,
    /// Join handle for the server task.
    join_handle: Option<tokio::task::JoinHandle<()>>,
    /// Receiver for tool requests from the IPC server.
    /// The agent loop polls this to dispatch tool calls.
    pub request_rx: mpsc::Receiver<PtcToolRequest>,
}

impl PtcIpcServer {
    /// Get the port the server is listening on.
    pub fn port(&self) -> u16 {
        self.port
    }

    /// Shut down the server gracefully.
    pub async fn shutdown(mut self) {
        if let Some(tx) = self.shutdown_tx.take() {
            let _ = tx.send(());
        }
        if let Some(handle) = self.join_handle.take() {
            let _ = handle.await;
        }
        debug!(port = self.port, "PTC IPC server stopped");
    }
}

impl Drop for PtcIpcServer {
    fn drop(&mut self) {
        // Best-effort shutdown on drop
        if let Some(tx) = self.shutdown_tx.take() {
            let _ = tx.send(());
        }
    }
}

/// Start the PTC IPC HTTP server on a random available port.
///
/// Returns the server and a receiver for tool requests. The caller (agent loop)
/// is responsible for polling the receiver and dispatching tool calls.
pub async fn start_ipc_server(
    ptc_tools: &[ToolDefinition],
) -> Result<PtcIpcServer, std::io::Error> {
    // Build tool name set for validation
    let tool_names: HashMap<String, ()> = ptc_tools
        .iter()
        .map(|t| (t.name.clone(), ()))
        .collect();
    let tool_names = Arc::new(tool_names);

    // Channel for tool requests: IPC server → agent loop
    let (request_tx, request_rx) = mpsc::channel::<PtcToolRequest>(32);

    // Bind to random port on localhost
    let listener = TcpListener::bind("127.0.0.1:0").await?;
    let port = listener.local_addr()?.port();

    let (shutdown_tx, shutdown_rx) = oneshot::channel::<()>();

    let join_handle = tokio::spawn(run_server(
        listener,
        tool_names,
        request_tx,
        shutdown_rx,
    ));

    debug!(port, "PTC IPC server started");

    Ok(PtcIpcServer {
        port,
        shutdown_tx: Some(shutdown_tx),
        join_handle: Some(join_handle),
        request_rx,
    })
}

/// Run the HTTP server loop.
async fn run_server(
    listener: TcpListener,
    tool_names: Arc<HashMap<String, ()>>,
    request_tx: mpsc::Sender<PtcToolRequest>,
    mut shutdown_rx: oneshot::Receiver<()>,
) {
    loop {
        tokio::select! {
            accept_result = listener.accept() => {
                match accept_result {
                    Ok((stream, _addr)) => {
                        let names = tool_names.clone();
                        let tx = request_tx.clone();
                        tokio::spawn(async move {
                            if let Err(e) = handle_connection(stream, names, tx).await {
                                warn!("PTC IPC connection error: {e}");
                            }
                        });
                    }
                    Err(e) => {
                        warn!("PTC IPC accept error: {e}");
                    }
                }
            }
            _ = &mut shutdown_rx => {
                debug!("PTC IPC server shutting down");
                break;
            }
        }
    }
}

/// Handle a single HTTP connection (one request-response).
///
/// Parses the HTTP request, validates the tool name, sends a request
/// to the agent loop via the channel, and waits for the result.
async fn handle_connection(
    mut stream: tokio::net::TcpStream,
    tool_names: Arc<HashMap<String, ()>>,
    request_tx: mpsc::Sender<PtcToolRequest>,
) -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
    use tokio::io::AsyncReadExt;

    // Read the full request (headers + body)
    let mut buf = vec![0u8; 65536];
    let mut total = 0;

    // Read until we have the full headers
    loop {
        let n = stream.read(&mut buf[total..]).await?;
        if n == 0 {
            return Ok(()); // Connection closed
        }
        total += n;

        if let Some(_header_end) = find_header_end(&buf[..total]) {
            break;
        }
        if total >= buf.len() {
            send_response(&mut stream, 413, "Request too large").await?;
            return Ok(());
        }
    }

    // Parse the request
    let header_end = match find_header_end(&buf[..total]) {
        Some(pos) => pos,
        None => {
            send_response(&mut stream, 400, "Malformed request").await?;
            return Ok(());
        }
    };

    let headers_str = std::str::from_utf8(&buf[..header_end]).unwrap_or("");
    let body_start = header_end + 4; // Skip \r\n\r\n

    // Parse method and path from first line
    let first_line = headers_str.lines().next().unwrap_or("");
    let parts: Vec<&str> = first_line.split_whitespace().collect();
    if parts.len() < 2 {
        send_response(&mut stream, 400, "Bad request line").await?;
        return Ok(());
    }

    let method = parts[0];
    let path = parts[1];

    // Only handle POST /tool/{name}
    if method != "POST" || !path.starts_with("/tool/") {
        send_response(&mut stream, 404, "Not found").await?;
        return Ok(());
    }

    let tool_name = urldecode(&path["/tool/".len()..]);

    // Validate tool exists
    if !tool_names.contains_key(&tool_name) {
        send_response(
            &mut stream,
            404,
            &format!("Tool not found: {tool_name}"),
        )
        .await?;
        return Ok(());
    }

    // Read Content-Length to get full body
    let content_length = parse_content_length(headers_str).unwrap_or(0);
    let body_available = total - body_start;

    // Read remaining body if needed
    let body = if content_length > body_available {
        let remaining = content_length - body_available;
        let mut extra = vec![0u8; remaining];
        let mut read = 0;
        while read < remaining {
            let n = stream.read(&mut extra[read..]).await?;
            if n == 0 {
                break;
            }
            read += n;
        }
        let mut full_body = buf[body_start..total].to_vec();
        full_body.extend_from_slice(&extra[..read]);
        full_body
    } else {
        buf[body_start..body_start + content_length.min(body_available)].to_vec()
    };

    // Parse JSON args
    let input: serde_json::Value = if body.is_empty() {
        serde_json::json!({})
    } else {
        match serde_json::from_slice(&body) {
            Ok(v) => v,
            Err(e) => {
                send_response(&mut stream, 400, &format!("Invalid JSON: {e}")).await?;
                return Ok(());
            }
        }
    };

    let tool_call_id = format!("ptc_{}_{}", tool_name, uuid::Uuid::new_v4());

    debug!(tool = %tool_name, "PTC IPC dispatching tool call");

    // Send request to agent loop and wait for result
    let (response_tx, response_rx) = oneshot::channel();
    let request = PtcToolRequest {
        tool_call_id,
        tool_name: tool_name.clone(),
        input,
        response_tx,
    };

    if request_tx.send(request).await.is_err() {
        send_response(&mut stream, 500, "Agent loop not available").await?;
        return Ok(());
    }

    // Wait for the result (with a generous timeout)
    match tokio::time::timeout(std::time::Duration::from_secs(300), response_rx).await {
        Ok(Ok(result)) => {
            if result.is_error {
                send_response(&mut stream, 500, &result.content).await?;
            } else {
                send_response(&mut stream, 200, &result.content).await?;
            }
        }
        Ok(Err(_)) => {
            send_response(&mut stream, 500, "Tool dispatch channel closed").await?;
        }
        Err(_) => {
            send_response(&mut stream, 500, "Tool execution timed out (300s)").await?;
        }
    }

    Ok(())
}

/// Send an HTTP response.
async fn send_response(
    stream: &mut tokio::net::TcpStream,
    status: u16,
    body: &str,
) -> Result<(), std::io::Error> {
    use tokio::io::AsyncWriteExt;

    let status_text = match status {
        200 => "OK",
        400 => "Bad Request",
        404 => "Not Found",
        413 => "Payload Too Large",
        500 => "Internal Server Error",
        _ => "Unknown",
    };

    let response = format!(
        "HTTP/1.1 {} {}\r\nContent-Type: text/plain; charset=utf-8\r\nContent-Length: {}\r\nConnection: close\r\n\r\n{}",
        status,
        status_text,
        body.len(),
        body
    );

    stream.write_all(response.as_bytes()).await?;
    stream.flush().await?;
    Ok(())
}

/// Find the end of HTTP headers (double CRLF).
fn find_header_end(buf: &[u8]) -> Option<usize> {
    buf.windows(4)
        .position(|w| w == b"\r\n\r\n")
}

/// Parse Content-Length from raw headers string.
fn parse_content_length(headers: &str) -> Option<usize> {
    for line in headers.lines() {
        let lower = line.to_lowercase();
        if let Some(stripped) = lower.strip_prefix("content-length:") {
            return stripped.trim().parse().ok();
        }
    }
    None
}

/// Simple URL decoding (percent-encoded chars).
fn urldecode(s: &str) -> String {
    let mut result = String::with_capacity(s.len());
    let mut chars = s.chars();
    while let Some(ch) = chars.next() {
        if ch == '%' {
            let hex: String = chars.by_ref().take(2).collect();
            if let Ok(byte) = u8::from_str_radix(&hex, 16) {
                result.push(byte as char);
            } else {
                result.push('%');
                result.push_str(&hex);
            }
        } else if ch == '+' {
            result.push(' ');
        } else {
            result.push(ch);
        }
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_find_header_end() {
        let data = b"GET / HTTP/1.1\r\nHost: localhost\r\n\r\nbody";
        assert_eq!(find_header_end(data), Some(33));
    }

    #[test]
    fn test_parse_content_length() {
        let headers = "POST /tool/file_read HTTP/1.1\r\nContent-Length: 42\r\nHost: localhost";
        assert_eq!(parse_content_length(headers), Some(42));
    }

    #[test]
    fn test_urldecode() {
        assert_eq!(urldecode("file_read"), "file_read");
        assert_eq!(urldecode("mcp_github%20list"), "mcp_github list");
        assert_eq!(urldecode("a%2Fb"), "a/b");
    }
}
